config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :users, only: [:new, :create]
  get 'login', to: 'users#login'
  post 'authenticate', to: 'users#authenticate'
  delete 'logout', to: 'users#logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
    @posts = Post.all
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to  login_path, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def login
  end

  def authenticate
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to posts_path, notice: 'Logged in successfully.'
    else
      flash.now[:alert] = 'Invalid email or password.'
      render :login
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to new_user_path, notice: 'Logged out successfully.'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar">
      <a class="navbar-brand" href="/">MyApp</a>

      <div class="navbar-links">
        <% if @current_user %>
          <span class="navbar-user">
            Logged in as <%= @current_user.admin? ? ' (Admin)' : '' %><%= @current_user.name %>
          </span>
          <%= turbo_frame_tag 'logout-link' do %>
            <%= form_with(url: logout_path, method: :delete) do |form| %>
              <%= form.submit 'Logout', class: 'btn btn-secondary' %>
            <% end %>
          <% end %>
        <% else %>
          <%= link_to 'Login', login_path, class: 'btn btn-primary' %>
        <% end %>
      </div>
    </nav>

    <div class="flash-messages">
      <% if flash[:notice] %>
        <div class="flash-message">
          <%= flash[:notice] %>
        </div>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1 class="heading">Edit Post</h1>

<%= form_with model: @post, url: post_path(@post), method: :patch do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1 class="heading">Posts</h1>

<ul>
  <% @posts.each do |post| %>
    <li class="box">

     <h2> <%= post.title %> </h2>
      <% if @current_user && @current_user.admin? %>
       <div style="display:flex; justify-content:space-around ;justify-content:center">
        <div><%= link_to 'Edit', edit_post_path(post), class: 'edit' %></div>
        <%= form_with url: post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete-button' do |form| %>
  <%= form.submit 'Delete' %>
<% end %>

      <% end %>
      <div><%= link_to 'show' , post_path(post) , class: 'show'%></div>
    </li>
  <% end %>
  </div>
</ul>

<% if @current_user && @current_user.admin? %>
  <b><%= link_to 'New Post', new_post_path , class:'new' %></b>
<% else %>
 <b> <%= link_to ' New Post', new_post_path , class:'new' %></b>
<% end %>

app/views/posts/new.html.erb
<h1 class="heading">New Post</h1>

<%= form_with model: @post, url: posts_path do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="box">
<h1 class="post-title"><%= @post.title %></h1>

<p class="post-content"><%= @post.content %></p>

<p class="post-author">Created by <%= @post.user.name %></p>

<%= link_to 'Edit', edit_post_path(@post), class: "edit-link" %> |
<%= link_to 'Back', posts_path, class: "back-link" %>
</div>

app/views/users/login.html.erb
<h1>Login</h1>

<%= form_with url: authenticate_path do |form| %>
  <% if flash[:alert] %>
    <div id="error_explanation">
      <h2><%= flash[:alert] %></h2>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_with model: @user, url: users_path do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>